# -*- coding: utf-8 -*-
"""NsfwDownloader.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BOqp-Yc_KcRTJV-DY1FHb8UglR7I3zmR
"""

import nekos
import requests
while 1==1:
  url = nekos.img('solo')
  dir1 = "/content/drive/MyDrive/Cat/NSFW"
  list1 = os.listdir(dir1)
  number_files = len(list1)
  name_file = str(number_files)
  if number_files > 1000:
    sys.exit()
  else:
    print('Downloading..')
    print('Hold Tight!')
    filename = ("nsfw." + name_file + ".jpg")
    r = requests.get(url)
    open(filename, 'wb').write(r.content)
    print('Done!')
    print('     ')